baseURL = "https://www.lisaduffin.com"
relativeURLs = true
languageCode = "en-us"
title = "Family and Parenting Coach | Lisa Duffin"


theme = "timer-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = false
defaultContentLanguage = "en"

[taxonomies]
  category = "categories"
  contributor = "contributors"
  tag = "tags"

[permalinks]
    articles = "/:title"
    categories = "/:title"
    landingpages = "/:title"


# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "About"
url     = "about"
weight  = 2
[[menu.main]]
name    = "Free Resources"
url     = "positive-parenting-mindset"
weight  = 3
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 4
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 5

# Site Params
[params]
home = "Home"
logo = "img/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Lisa Duffin family and parenting coach. Creator of the Transformative Parenting Technique"
author = "Lisa Duffin"

# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "img/headers/family-coaching-banner.jpg"
heading = "Family Coaching"
description = "Empowering Mothers and Fathers to Parent with Purpose"
# button
btn     = true
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "MOTHERS"
[[params.banner.flipText]]
title   = "FATHERS"
[[params.banner.flipText]]
title   = "PARENTS"
[[params.banner.flipText]]
title   = "FAMILIES"

# Homepage Opening Section
[params.opening]
image   = "img/question-mark3.jpg"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"
content = "Hi, I’m Lisa and I work with parents, just like you who are tired of wading through the plethora of parenting information out there. Mothers and fathers who are confused by the differing ‘best practise parenting’ messages and are scratching their heads trying to figure out what will work for them. Parents who are looking for personalised solutions that truly work for their unique family dynamic. Mothers and fathers, just like you who want to excel as parents."
image   = "img/lisa-duffin-family-coach.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "Yes, I’m Interested"
content = "Book me in for a free discovery call to learn more"
btnText = "Book Call Now"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/groups/parentingyourinnerchild"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/lisaduffin_coach"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
